spring:
  application:
    name: poe-companion

  datasource:
    url: jdbc:postgresql://${POE_COMPANION_DB_HOST}:${POE_COMPANION_DB_PORT}/${POE_COMPANION_DB_NAME}
    username: ${POE_COMPANION_DB_USER}
    password: ${POE_COMPANION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    create-schemas: true
    default-schema: poe_companion
    locations: classpath:db/migration
    validate-migration-naming: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: poe_companion
