[versions]
forbiddenapis = "3.11"
lombok = "9.7.0"
dependencyManagement = "1.1.7"
cyclonedx-bom = "3.4.1"
spring-boot = "4.1.1"

[libraries]
org-postgresql-postgresql = { group = "org.postgresql", name = "postgresql" }
org-springframework-boot-springBootDevtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
org-springframework-boot-springBootDockerCompose = { group = "org.springframework.boot", name = "spring-boot-docker-compose" }
org-springframework-boot-springBootStarterActuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
org-springframework-boot-springBootStarterDataJpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
org-springframework-boot-springBootStarterLiquibase = { group = "org.springframework.boot", name = "spring-boot-starter-liquibase" }
org-springframework-boot-springBootStarterTest = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
org-springframework-boot-springBootStarterValidation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
org-springframework-boot-springBootStarterWeb = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
org-springframework-boot-springBootStarterWebmvcTest = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
org-springframework-boot-springBootTestcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers" }
org-testcontainers-junitJupiter = { group = "org.testcontainers", name = "testcontainers-junit-jupiter" }
org-testcontainers-postgresql = { group = "org.testcontainers", name = "testcontainers-postgresql" }

[plugins]
de-thetaphi-forbiddenapis = { id = "de.thetaphi.forbiddenapis", version.ref = "forbiddenapis" }
io-freefair-lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
io-spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "dependencyManagement" }
org-cyclonedx-bom = { id = "org.cyclonedx.bom", version.ref = "cyclonedx-bom" }
org-springframework-boot-springBoot = { id = "org.springframework.boot", version.ref = "spring-boot" }
